### ISSUE TITLE
Login Page is not working

### ISSUE THREAD

**Issue by Latish705** [The-Xiting-Way/DevXClub#1]
# On clicking the google login button it is not working
<img width="1440" alt="image" src="https://github.com/The-Xiting-Way/DevXClub/assets/104522651/754c7ea4-49ac-4620-a8d6-b08e844d9dbb">
- try to fix that and the design is not responsive
-  need to make design responsive

**Comment by mohdjami** [comment]
Hi @Latish705 . I want to work on this issue. Please assign this issue to me under GSSoC'24.

**Comment by Latish705** [comment]
@Gurpreet0798 @Sa2003hil @Aryainguz assing him this issue as I am not the contributor

**Comment by Aryainguz** [comment]
@mohdjami sure go ahead we’ll love to see what you can come up with!

**Comment by MishraTanishq619** [comment]
I am able to work with NextAuth , I can do for this issue

**Comment by mohdjami** [comment]
Hi @MishraTanishq619 , I am already assigned and working on this one.

**Comment by Aryainguz** [comment]
@MishraTanishq619 we need nexauth for this so you can take it from here and do let us know if you need any help! Go ahead

**Comment by Aryainguz** [comment]
@mohdjami you can create a new PR fixing the layout and design part of this page while @MishraTanishq619 works on next Auth part you guys can also co ordinate on this, thanks!

**Comment by mohdjami** [comment]
@Aryainguz I have already completed the login part using Next-auth. I will raise a PR after some fixes.

**Comment by mohdjami** [comment]
I have raised a PR implementing Login functionality using Next-auth. Please let me know if there are any issues.

https://github.com/The-Xiting-Way/DevXClub/assets/114595881/85c3272c-9dc8-488a-8cc3-18d8343b2107

**Comment by mohdjami** [comment]
@Aryainguz Please label the issues as per the guidelines, like level3, gssoc and reassign the issue to me, otherwise my contribution won't be counted.

**Comment by Gurpreet0798** [comment]
Ok sure! @mohdjami
