### ISSUE TITLE
[Feature]: Develop Responsive Project Page

### ISSUE THREAD

**Issue by Vaibhavsg17** [The-Xiting-Way/DevXClub#16]
@Aryainguz i would like to develop project page under the GSSOC'24 tag

**Comment by Aryainguz** [comment]
Go ahead and add projects like DevXChat, DevXMeet, etc these are projects we’re planning to develop in house exclusively for our community, will love if you add cool animations and stuff on this page @Vaibhavsg17

**Comment by Gurpreet0798** [comment]
Hii @Vaibhavsg17 could i please know that how you are planning to contribute to the project. Can you please provide me the complete description about how you are going to execute your plan with some sort of ss of the work you have done till now...

**Comment by Vaibhavsg17** [comment]
Hello @Aryainguz & @Gurpreet0798 , I was busy with my semester exams. I am starting from today,  I'm facing issues with the env file how can I get the database URL & NEXT_PUBLIC_APP_URL
