### ISSUE TITLE
[Feature] improve Not found page

### ISSUE THREAD

**Issue by ronisarkarexe** [The-Xiting-Way/DevXClub#19]
We can improve our page not found page.

![devxnotfound](https://github.com/The-Xiting-Way/DevXClub/assets/76697055/cded13bd-d3d3-4ea5-af1e-a365671545ad)

**Comment by ronisarkarexe** [comment]
@sanjay-kv please assign me this issue.

**Comment by vignesh-0512** [comment]
I am willing to work on this issue i would like to increase the UI of 404 not found page and also I have an experience in building attractive UI of 404 not found page, so I would request you to assign this issue under Gssoc'24.

**Comment by Aryainguz** [comment]
@ronisarkarexe @vignesh-0512 both of you can work on this

**Comment by vignesh-0512** [comment]
@Aryainguz Thanks for assigning me this issue, I will develop it and raise PR as soon as possible.
