### ISSUE TITLE
[BUG] - Links not working.

### ISSUE THREAD

**Issue by NilanchalaPanda** [The-Xiting-Way/DevXClub#2]
Different links on the website are not working, that is, there are mainly two issue : 
      - Either the link tag is not attached with the button. (Eg : Get started Now).
      - Or the tags redirect to 404 pages (Eg : About, Contact, Projects).
 
I would love to your upon this issue and contribute to DevXClub as a GSSoC'24 contributor. Looking forward to your response.
      
IMAGE : 
![image](https://github.com/The-Xiting-Way/DevXClub/assets/110488337/a664e757-aaae-4a9f-ba7d-dc5fae39e634)

**Comment by Anayverma** [comment]
hi @NilanchalaPanda , I would like to solve this issue . Please assign it to me under gssoc24.

**Comment by NilanchalaPanda** [comment]
Hello @Anayverma, I myself want to work on the issue. That's why I have raised it and also mentioned about it in the description of the issue. You can raise another issue for the same.

Happy Hacking!

**Comment by Aryainguz** [comment]
@NilanchalaPanda links aren’t working since this project is under development, we’ll appreciate if you want to add you part on new pages!

**Comment by NilanchalaPanda** [comment]
Thanks for the update @Aryainguz 🙌🏻. Will start working on DevXClub.
