### ISSUE TITLE
feature: add authentication with clerkjs

### ISSUE THREAD

**Issue by Shobhit-Nagpal** [The-Xiting-Way/DevXClub#21]
hey! i noticed that the signin page for the site is not functional yet and would love work on this under gssoc' 24.

currently, there's 4 buttons with the google logo on it. i assume it's meant to be different oauth providers.

![image](https://github.com/The-Xiting-Way/DevXClub/assets/74096450/93bd8780-c523-4c20-b026-dd1a5f477981)

i'll help integrate clerk with this and revamp the authentication flow with clerk. let me know the different oauth providers you had in mind :)

**Comment by amjido-01** [comment]
i can also work on this, can I get assign

**Comment by Aryainguz** [comment]
It’s already been assigned in another issue, please add your comments there,
Thanks!
