### ISSUE TITLE
Footer section.

### ISSUE THREAD

**Issue by amjido-01** [The-Xiting-Way/DevXClub#25]
I can work on a nice footer for the site, please assign me under gssoc`24

**Comment by amjido-01** [comment]
@Aryainguz so I don't know the links to be included on this footer section. Do you mind giving a list of them

**Comment by anshikatiwari20** [comment]
**Description:**
The footer section of the website needs enhancements to improve its functionality and visual appeal.

**Screenshot:**
![Screenshot 2024-06-19 105856](https://github.com/The-Xiting-Way/DevXClub/assets/143124119/ed87753e-2a9d-458e-85fd-0ee17ae85dbd)

@Aryainguz I am a GSSoC contributor and would like to work on the footer section as described in issue #25. Could you please assign this issue to me? Thank you!
