### ISSUE TITLE
[Feature] Dark mode

### ISSUE THREAD

**Issue by Ankitapanda25** [The-Xiting-Way/DevXClub#29]
there could be a dark mode feature, it would probably look good. 

@sanjay-kv please assign me this under GSSOC'24

**Comment by sanjay-kv** [comment]
We dont have website to apply the dark mode yet. Where you plan to implement this?

**Comment by Ankitapanda25** [comment]
@sanjay-kv currently it could be added to the homepage, and soon after other pages are added

**Comment by sanjay-kv** [comment]
I'm not the admin of repo. I can't assign here for issues . Thanks

**Comment by Aryainguz** [comment]
@Ankitapanda25 thanks for pointing this crucial feature, please go ahead with this we will highly appreciate it to be done

**Comment by Ankitapanda25** [comment]
Thanks for assigning! working on it!

**Comment by mohdjami** [comment]
Hi, @Aryainguz in my recent PR for Login Page I have already implemented Dark Mode. Please have a look in the attached video of #1 issue. I didnt see this issue here before implementing it.
