### ISSUE TITLE
Issue: Lack of Label or Mention for Black Button Opening Signup Page

### ISSUE THREAD

**Issue by bro-maanii** [The-Xiting-Way/DevXClub#30]
The black button in question, when clicked, opens the signup page without any label or mention indicating its function as a signup or login button.

## Details
The black button's purpose is to direct users to the signup page upon clicking. However, there is no clear label or mention associated with the button indicating that it serves as a signup or login button. This lack of clarity can confuse users about the button's functionality and intended action.

## Steps to Reproduce

1- Visit the page where the black button is located.
2- Observe the black button's appearance and placement.
3- Click on the black button.

![image](https://github.com/The-Xiting-Way/DevXClub/assets/125199246/df193b1f-faed-43ce-a874-bada2b657e24)

**Comment by Aryainguz** [comment]
Sure, you can work on this @bro-maanii
