### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Aryainguz** [The-Xiting-Way/DevXClub#33]
Update readme with relevant images and clean structure

**Comment by PrathicaShettyM** [comment]
@sanjay-kv @ronisarkarexe @Sa2003hil @Gurpreet0798 Can please assign me this task under GSSoC'24?

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by Aryainguz** [comment]
go ahead @PrathicaShettyM

**Comment by PrathicaShettyM** [comment]
Yes sir sure
