### ISSUE TITLE
Testimonial section 

### ISSUE THREAD

**Issue by Anamika-Ratna** [The-Xiting-Way/DevXClub#34]
I would like to add a testimonial section on the home page after "turn your ideas into reality" section .
If you like this idea, kindly assign me this issue under gssoc tag.

**Comment by Aryainguz** [comment]
go ahead on this @Anamika-Ratna

**Comment by bro-maanii** [comment]
Hi @Aryainguz ,
I noticed that this issue has not had any updates since it was assigned last week and no PR has been created yet. If @Anamika-Ratna cannot work on it, please reassign the issue to me. I am available and would be happy to work on it immediately.
Thank you!
