### ISSUE TITLE
contributor's section 

### ISSUE THREAD

**Issue by Anamika-Ratna** [The-Xiting-Way/DevXClub#35]
I would like to add a contributor's section at the bottom of the page where the profile of those who contributed to the project will be displayed. 
If you like this issue, kindly assign this to me under gssoc tag.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
