### ISSUE TITLE
[Enhancement] Styling of Scrollbar

### ISSUE THREAD

**Issue by MishraTanishq619** [The-Xiting-Way/DevXClub#38]
We must style the scrollbar.
Its styles should be align with the theme of our website.

**Comment by MishraTanishq619** [comment]
I would Like to work on this myself.
Please assign me this, for GSSOC.

**Comment by Aryainguz** [comment]
Sure go ahead @MishraTanishq619

**Comment by MishraTanishq619** [comment]
![Screenshot from 2024-05-20 10-28-20](https://github.com/The-Xiting-Way/DevXClub/assets/127047332/a4320a3a-191b-4fcb-845c-5a6ffcb3110a)
![Screenshot from 2024-05-20 10-28-01](https://github.com/The-Xiting-Way/DevXClub/assets/127047332/5121b38f-54df-4eb3-a9a4-ccf2dd491f0a)


Any suggestions on which one to go with.

**Comment by MishraTanishq619** [comment]
Well, I had made a PR of second one.
If any suggessions , Feel free to share.
