### ISSUE TITLE
[BUG] Navbar is not working in About and Contact page.

### ISSUE THREAD

**Issue by mohdjami** [The-Xiting-Way/DevXClub#47]
Navbar is not visible in any section other than landing page. Assign this issue to me I will fix it.

**Comment by anshikatiwari20** [comment]
**Description:**
The navbar is currently not working on the About and Contact pages. This issue can affect navigation and the overall user experience. I would like to fix the problem by ensuring the navbar functions correctly on these pages.

**Screenshot:**
![Screenshot 2024-06-19 111104](https://github.com/The-Xiting-Way/DevXClub/assets/143124119/088dafac-d46c-4dde-8f02-c29338780618)

I am a GSSoC contributor and would like to work on fixing the navbar issue on the About and Contact pages as described in issue #47. Could you please assign this issue to me and add the GSSoC label? Thank you!
