### ISSUE TITLE
[Feature] Add an About Page

### ISSUE THREAD

**Issue by Manav173** [The-Xiting-Way/DevXClub#51]
Is your feature request related to a problem? Please describe.

Users often express frustration when they cannot easily find information about our company, our mission, and the team behind our products. This lack of transparency can lead to mistrust or a sense of detachment from our brand. An About Page is crucial for providing this information in a clear and accessible manner.

Describe the solution you'd like

We propose the addition of an About Page to our website. This page will provide comprehensive information about our company, including our history, mission, values, and team members. It will also highlight our commitment to quality, customer satisfaction, and any unique aspects that set us apart from our competitors. The page should be easily accessible from the main navigation menu.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @The-Xiting-Way .

**Comment by Aryainguz** [comment]
Go ahead @Manav173
