### ISSUE TITLE
Issue : Missing "Contact Us" Page

### ISSUE THREAD

**Issue by bro-maanii** [The-Xiting-Way/DevXClub#54]
Summary
The website currently lacks a "Contact Us" page, which is essential for users to reach out for support, inquiries, or feedback.

Details
A "Contact Us" page is a fundamental feature that provides users with a way to communicate with the website's team. It typically includes a contact form, email address, phone number, and sometimes additional information like office locations and social media links. The absence of this page makes it difficult for users to get in touch with the website administrators.

**Comment by Gurpreet0798** [comment]
You are right @bro-maanii 
Can you please provide me some description on how you are planning to do this and achieve this.
You can give me a random idea through a ss of your own work or something else.

**Comment by bro-maanii** [comment]
@Gurpreet0798  The current "Contact Us" page lacks a few essential elements:

Navigation Bar: Adding a navbar will allow users to navigate back to the home page or other sections of the site easily.
Footer: Including a footer will provide a consistent look and feel with the rest of the website and offer additional navigation or information.
Submit Button: The contact form needs a submit button below it to allow users to send their messages or inquiries.

![image](https://github.com/The-Xiting-Way/DevXClub/assets/125199246/ee82d4d8-5aac-4f75-9e94-e3e6870face4)

**Comment by bro-maanii** [comment]
![image](https://github.com/The-Xiting-Way/DevXClub/assets/125199246/95deaa97-006b-40d9-86e4-f9fa262a5805)

i want contact us Page to look like this @Gurpreet0798

**Comment by Aryainguz** [comment]
Go ahead but keep it in similar ui @bro-maanii
