### ISSUE TITLE
Creating the Login and Signup page UI

### ISSUE THREAD

**Issue by CoderSwarup** [The-Xiting-Way/DevXClub#57]
their is no login and signup page on the website when user click on the get  started button he redirect to register page but he get a 404 error page 

please assign me this issue i want to work on this issue 

if any design available please provide me that

**Comment by Aryainguz** [comment]
Go ahead @CoderSwarup

**Comment by CoderSwarup** [comment]
@Aryainguz  check ui

![image](https://github.com/The-Xiting-Way/DevXClub/assets/128630311/db49a41a-1d83-476f-ab31-c7895f5f7b23)

and their is login page already build can i change that 

![image](https://github.com/The-Xiting-Way/DevXClub/assets/128630311/19980ac5-cf01-44ac-aed1-b1a3270c0f4a)
