### ISSUE TITLE
Feature: Adding Responsive Reviews Section Using  Aceternity UI for building customer trust 

### ISSUE THREAD

**Issue by Aniket-2504** [The-Xiting-Way/DevXClub#58]
Hello @Aryainguz ,

I hope this message finds you well.

#  I have a suggestion to enhance customer trust on the DevXClub website. 

### Currently, you mention 6+ years in business and 4821 projects delivered, which is impressive. However, adding a responsive reviews section using Aceternity UI could further strengthen customer trust by showcasing real feedback from satisfied clients.

# Benefits:

1. Enhances credibility and trustworthiness.
2. Building Customer Trust with DevXclub
3. Provides potential customers with authentic testimonials.
4. Improves user engagement and satisfaction.

I would love to work on this feature and implement it effectively. Could you please assign this task to me? I am confident that I can deliver the best results.

I look forward to your response.

**Comment by Aryainguz** [comment]
Great idea go ahead @Aniket-2504

**Comment by Aniket-2504** [comment]
Thanks a lot @Aryainguz , appreciate you , I will give my best possible

**Comment by sri766** [comment]
Hello @Aryainguz , May I contribute to this under GSSOC'24 too.
