### ISSUE TITLE
feat: adding favicon and metadata

### ISSUE THREAD

**Issue by TenzDelek** [The-Xiting-Way/DevXClub#69]
the current favicon and metadata are the default one 
<img width="143" alt="image" src="https://github.com/The-Xiting-Way/DevXClub/assets/122612557/ca68beef-3c77-4adf-a2f0-b2634f26a34c">

**Comment by ManjariRathore** [comment]
please assign me this issue . Pretty Please <3.

**Comment by TenzDelek** [comment]
the code owner is inactive. you can either wait or explore different repo.

**Comment by ManjariRathore** [comment]
@TenzDelek thankyou
