### ISSUE TITLE
Changing font colour to make the site more readable

### ISSUE THREAD

**Issue by MadhurimaNayak** [The-Xiting-Way/DevXClub#80]
### Description

The font color could be changed in a few places to make the text clearer to the user. This would enhance the user experience. I have attached a few screenshots as examples.

### Solution

I would change the colour of these texts, keeping in mind the website's overall colour scheme.

### Screenshots

![image](https://github.com/The-Xiting-Way/DevXClub/assets/124715194/8b771614-1958-408d-8dc1-4d11cacafa41)
![image](https://github.com/The-Xiting-Way/DevXClub/assets/124715194/717bf421-4594-4669-a437-96fc04d8db5e)
![image](https://github.com/The-Xiting-Way/DevXClub/assets/124715194/98b86dab-0b07-43fe-affd-962505fb2318)
![image](https://github.com/The-Xiting-Way/DevXClub/assets/124715194/af1dc241-d4cc-4b0a-8d06-9b317a37c1d3)

**Comment by MadhurimaNayak** [comment]
hey @Aryainguz, please assign this issue to me.

**Comment by AkhilaSunesh** [comment]
I would be interested in working for this issue. Please assign me.
