### ISSUE TITLE
Enhancing the Navbar 

### ISSUE THREAD

**Issue by aanchalpahuja18** [The-Xiting-Way/DevXClub#84]
Enhancing the Navbar UI will make the website look more pleasing 
![image](https://github.com/The-Xiting-Way/DevXClub/assets/136963878/7adb1dbf-0fb9-4d6d-bb39-e49edfbc05fc)

**Comment by aanchalpahuja18** [comment]
@Gurpreet0798 kindly assign me this issue I will solve it really quick

**Comment by Vibhuti270** [comment]
Please assign this issue to me I have worked with acertinityUI I will enhance navbar
Please assign issue under ggsoc'24

**Comment by ManjariRathore** [comment]
@Gurpreet0798  please assign this issue to me . Pretty Please <3 .
